#!/usr/bin/env python3
# Emit LaTeX snippets for RALE per_seed and per_method tables (SMACv2 warm).
from __future__ import annotations

import csv
from pathlib import Path

Ks = [8, 12, 16, 20, 24, 32, 64, 128]
ROOT = Path(__file__).resolve().parents[3] / "results" / "phase2_rale_alignment"


def f(x: str) -> float:
    return float(x) if x not in ("", "nan", None) else float("nan")


def load(path: Path) -> dict[tuple[int, str], dict]:
    with path.open(newline="") as fp:
        return {(int(r["K"]), r["method"]): r for r in csv.DictReader(fp)}


def main() -> None:
    out_ps: list[str] = []
    out_pm: list[str] = []
    hdr = "% Auto-generated by export_rale_paper_tables.py\n"

    out_ps.append("% --- per (method, seed) k-means ---\n")
    out_ps.append("\\begin{tabular}{cccccccc}\n\\toprule\n")
    out_ps.append(
        "$N$v$4$ & $K$ & "
        r"$\rho_w^{\mathrm{AL}}$ & $\Delta\rho_w^{\mathrm{AL}}$ & "
        r"$A_{\mathrm{iso}}^{\mathrm{AL}}$ & "
        r"$\rho_w^{\mathrm{MP}}$ & $\Delta\rho_w^{\mathrm{MP}}$ & "
        r"$A_{\mathrm{iso}}^{\mathrm{MP}}$ "
        "\\\\\n\\midrule\n"
    )
    for N in (2, 4, 8):
        d = load(ROOT / f"smacv2_{N}v4_warm/analysis_z_per_seed/tables/method_aggregate.csv")
        for K in Ks:
            a, m = d[(K, "alec")], d[(K, "rl_warm")]
            ra, sa = f(a["ws_mean"]), f(a["shuffle_ws"])
            rm, sm = f(m["ws_mean"]), f(m["shuffle_ws"])
            out_ps.append(
                f"{N} & {K} & ${ra:.3f}$ & ${ra - sa:+.2f}$ & ${f(a['aiso_mean']):.3f}$ & "
                f"${rm:.3f}$ & ${rm - sm:+.2f}$ & ${f(m['aiso_mean']):.3f}$ \\\\\n"
            )
        if N != 8:
            out_ps.append("\\midrule\n")
    out_ps.append("\\bottomrule\n\\end{tabular}\n")

    out_pm.append("% --- per method (pooled seeds) k-means ---\n")
    out_pm.append("\\begin{tabular}{cccccccccc}\n\\toprule\n")
    out_pm.append(
        "$N$v$4$ & $K$ & val AL & val MP & "
        r"$\rho_w^{\mathrm{AL}}$ & $\Delta\rho_w^{\mathrm{AL}}$ & "
        r"$A_{\mathrm{iso}}^{\mathrm{AL}}$ & "
        r"$\rho_w^{\mathrm{MP}}$ & $\Delta\rho_w^{\mathrm{MP}}$ & "
        r"$A_{\mathrm{iso}}^{\mathrm{MP}}$ "
        "\\\\\n\\midrule\n"
    )
    for N in (2, 4, 8):
        d = load(ROOT / f"smacv2_{N}v4_warm/analysis_z_per_method/tables/method_aggregate.csv")
        for K in Ks:
            a, m = d[(K, "alec")], d[(K, "rl_warm")]
            ra, sa = f(a["ws_mean"]), f(a["shuffle_ws"])
            rm, sm = f(m["ws_mean"]), f(m["shuffle_ws"])
            ca = a["n_seeds_valid"] + "/" + a["n_seeds_total"]
            cmm = m["n_seeds_valid"] + "/" + m["n_seeds_total"]
            out_pm.append(
                f"{N} & {K} & {ca} & {cmm} & ${ra:.3f}$ & ${ra - sa:+.2f}$ & ${f(a['aiso_mean']):.3f}$ & "
                f"${rm:.3f}$ & ${rm - sm:+.2f}$ & ${f(m['aiso_mean']):.3f}$ \\\\\n"
            )
        if N != 8:
            out_pm.append("\\midrule\n")
    out_pm.append("\\bottomrule\n\\end{tabular}\n")

    d1 = ROOT / "rale_table_per_seed_method.tex"
    d2 = ROOT / "rale_table_per_method_pooled.tex"
    d1.write_text(hdr + "".join(out_ps))
    d2.write_text(hdr + "".join(out_pm))
    print(d1, d2, sep="\n")


if __name__ == "__main__":
    main()
